config/routes.rb
Rails.application.routes.draw do
  root 'pages#index'

  
devise_for :users, :controllers => { registrations: 'registrations' }
  resources :paragraphs,  :except => :show do
  member do
    post 'upvote'
    post 'publish'
  end
end
  
  get 'write' => 'paragraphs#new' 
  
  get 'vote' => 'paragraphs#index'
  
  

end

app/models/paragraph.rb
class Paragraph < ActiveRecord::Base
  
  belongs_to :user
  belongs_to :page
  has_many :votes, dependent: :destroy

  validates_presence_of :parag
  validates_length_of :parag, minimum: 200, maximum: 3000
  
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_many :paragraphs
  
  validates_presence_of :first_name,:last_name
  validates_length_of :first_name,:last_name, maximum: 20, message: "must be less than 20 charactes long"
  validates_length_of :first_name,:last_name, minimum: 2, message: "must be more than 2 charactes long"
  
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/vote.rb
class Vote < ActiveRecord::Base
  belongs_to :paragraph
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead. 
  protect_from_forgery with: :exception
  before_filter :configure_permitted_parameters, if: :devise_controller?

  protected

  def authenticate_user!
    if user_signed_in?
      super
    else
      redirect_to new_user_session_path, :notice => 'Please login first! :)'
      ## if you want render 404 page
      ## render :file => File.join(Rails.root, 'public/404'), :formats => [:html], :status => 404, :layout => false
    end
  end
  
  def check_admin!
  redirect_to root_path, notice: 'You dont have enough permissions to be here ;)' unless current_user && current_user.admin?
  end
  
  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:name, :email, :password) }
    devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:name, :email, :password, :current_password, :is_female, :date_of_birth) }
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def index
    @last_page = Paragraph.where(:main => true ).last.main_id.to_i
    
    @page = params['page'].to_i
    @prev_page = @page - 1 unless @page <= 1
    @next_page = @page + 1 unless @page >= @last_page 
    
    if @next_page == nil
      @next_page = @last_page
    end
    
    @paragraphs = Paragraph.where( :main => true, :main_id => @page).order("created_at")
    
  end

  private
  
  def page_params
  params.require(:page).permit(:page_id, :chapter, :text)
  end
  
end

app/controllers/paragraphs_controller.rb
class ParagraphsController < ApplicationController
  before_filter :authenticate_user!
  before_filter :check_admin!, only: [:publish]  
  
  before_action :set_paragraph, only: [:show, :edit, :update, :destroy]

  # GET /paragraphs
  # GET /paragraphs.json
  def index
    @paragraphs = Paragraph.where(:main => nil).order('created_at DESC').paginate(:page => params[:page], :per_page => 1)
    @para_last = Paragraph.where(:main => true).last
  end

  # GET /paragraphs/new
  def new
    @para_last = Paragraph.where(:main => true).last
    @paragraph = Paragraph.new
  end

  # GET /paragraphs/1/edit
  def edit
    @paragraph = set_paragraph
    
    if current_user.id != @paragraph.user_id
      redirect_to :back
    end
  end

  # POST /paragraphs
  # POST /paragraphs.json
  def create
    @paragraph = Paragraph.new(paragraph_params)
    @paragraph.author = author
    @paragraph.user = current_user
    
    respond_to do |format|
      if @paragraph.save
        format.html { redirect_to vote_path, notice: 'Paragraph was successfully created.' }
        format.json { render :show, status: :created, location: @paragraph }
      else
        format.html { render :new }
        format.json { render json: @paragraph.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /paragraphs/1
  # PATCH/PUT /paragraphs/1.json
  def update
    @paragraph = set_paragraph
    @paragraph.votes.destroy_all
    
    if current_user.id != @paragraph.user_id
      redirect_to :back
    end
    
    respond_to do |format|
      if @paragraph.update(paragraph_params)
        format.html { redirect_to vote_path, notice: 'Paragraph was successfully updated.' }
        format.json { render :show, status: :ok, location: @paragraph }
      else
        format.html { render :edit }
        format.json { render json: @paragraph.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /paragraphs/1
  # DELETE /paragraphs/1.json
  def destroy
    @paragraph.destroy
    
    respond_to do |format|
      format.html { redirect_to vote_path, notice: 'Paragraph was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  
  def upvote
    @paragraph = set_paragraph

    if @paragraph.votes.where(:user_id => current_user.id).exists? 
      
      redirect_to :back, notice: 'You can only vote once per paragraph ;)'
    else
      @paragraph.votes.create(:user_id => current_user.id)
      redirect_to :back
    end
  end
  
  def publish
   
    last_page = 0
    
    Paragraph.where(:main => true ).each do |para|  
      if para.main_id.to_i > last_page
        last_page = para.main_id
      end
    end
    
    @paragraph = set_paragraph
    @paragraph.main = true
    
    if if_enough?(@paragraph.parag.length, last_page) 
      @paragraph.main_id = last_page
      @paragraph.save
    else
      @paragraph.main_id = last_page.to_i + 1 
      @paragraph.save
    end
    
    Paragraph.where(:main_id => nil).destroy_all
    redirect_to :back
  end
  
  private
 
  def admin?
    self.admin == true
  end
 
  def author
    return "#{current_user.first_name} #{current_user.last_name}"
  end
  
  def if_enough?(this_para_length, last_page)
    temp = 0
    a = Paragraph.where(:main => true , :main_id => last_page)
    
    a.each do |paragraph|
      temp += paragraph.parag.length
    end
    
    if (temp + this_para_length) < 5000
      return true
    else
      return false
    end 
    
  end
  
  def set_paragraph
    @paragraph = Paragraph.find(params[:id])
  end
  
  # Never trust parameters from the scary internet, only allow the white list through.
  def paragraph_params
    params.require(:paragraph).permit(:author, :parag, :main, :main_id)
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  def new
    super
  end

  def create
    super
  end

  def update
    super
  end
  
   def sign_up_params
    params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation)
  end
  
  def account_update_params
    params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation, :current_password)
  end
end 

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/paragraphs_helper.rb
module ParagraphsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>WrittenByTheInternet</title>
  <%= favicon_link_tag 'favicon.ico' %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>

  <%= csrf_meta_tags %>
</head>
<body>
<%= render "shared/header" %>
  <%= javascript_include_tag :defaults %>
  
  <% if %>
  <%= render "shared/nav" %>
  
<div class= "content">
  <% if notice != nil %>
   <div class="notice"><%= notice %></div>
  <% end %>
  <% if alert != nil %>
       <div class="alert"><%= alert %></div>
  <% end %>

    <%= yield %>
</div>
  <% else %>
  <% redirect_if_not_user %>
  <% end %>
<%= render "shared/footer" %>
</body>
</html>

app/views/pages/index.html.erb
<div class= "pages">
  <div class= "top">
    
    <div class="page"><%= @page + 1 %></div>  
  </div>
  <div class = "cont">
    
    <% @paragraphs.each do |paragraph| %>
    <div class="newpara"> 
      <p class="author">written by <br><%= paragraph.author %>
        
      <% if current_user.try(:id) ==  paragraph.user_id %>
        (you)</p>
      <% else %>
        </p>
      <% end %>
      <p class="text"> <%= paragraph.parag %></p>
    </div>
    <% end %>

    <div class= "bottom">
      <div class="pagin">
      
        <%= link_to '<<' , root_path %>
        <%= link_to 'prev', root_path(:page => @prev_page) %>
        <%= link_to 'next', root_path(:page => @next_page) %>
        <%= link_to '>>' , root_path(:page => @last_page) %>

    </div>
 
      </div>
  </div>
</div>

app/views/paragraphs/_form.html.erb
<%= form_for(@paragraph) do |f| %>
  <% if @paragraph.errors.any? %>
    <div class="alert">
      <h2><%= pluralize(@paragraph.errors.count, "error") %> prohibited this paragraph from being saved:</h2>
      <ul>
      <% @paragraph.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
<%= link_to 'Back', write_path(@paragraph) %>
  <% else %>
    <div class="field">
      <%= f.label :parag, 'Write your own paragraph below:'%><br>
      <%= f.text_area :parag ,:placeholder => 'Text goes here ;)'%>
    </div>

    <div class="actions">
      <%= f.submit %>
    </div>
  <% end %>
<% end %>

app/views/paragraphs/edit.html.erb
<div class = "instructions">
  <p class = "h_field">Editing</p>
  <p>Editing will erase all current votes!</p>
</div>

<%= render 'form' %>

<%= link_to 'Back', vote_path %>

app/views/paragraphs/index.html.erb
<% if @para_last != nil %>
  <div class = "cont">Last published paragraph:<br>
    <div class="newpara"> 
        <p class="author">written by <br> <%= @para_last.author %>
          <% if current_user.try(:id) ==  @para_last.user_id %>
            <br>(you)</p>
          <% else %>
            </p>
          <% end %>
        <p class="text"> <%= @para_last.parag %></p>
    </div>
  </div>
<% end %>

<div class = "instructions">
<p class = "h_field">Upvote best paragraph propositions</p>
<p>and watch them get published.</p>
</div>

<div class = "cont">
  <% @paragraphs.each do |paragraph| %>
    <div class="newpara"> 
      <p class="author">proposed by <br><%= paragraph.author %>
        <% if current_user.id ==  paragraph.user_id %>
          <br>(you)</p>
        <% else %>
          </p>
        <% end %>
      <p class="text"> <%= paragraph.parag %></p>
    </div>
    <br>
    </div>

    

    <div class = "votebutton">
      <%   if current_user.try(:admin?) == true %>
        <%= button_to 'publish', publish_paragraph_path(paragraph), method: :post %>
      <% end %>
      
      <% if current_user.id !=  paragraph.user_id %>
        <%= button_to '+1', upvote_paragraph_path(paragraph), method: :post %>
      <% end %>
      <% if current_user.id ==  paragraph.user_id || current_user.admin?%>

      <%= link_to 'Edit', edit_paragraph_path(paragraph) %>
      <%= link_to 'Delete', paragraph, method: :delete, data: { confirm: 'Are you sure?' } %>

      <% end %>  
   
      
      
      <%= pluralize(paragraph.votes.count, "vote") %>
       </div>
     
   <% end %>
<%= will_paginate @paragraphs , :page_links => false , :next_label => 'Next', :previous_label => 'Previous' %>
<%= @votes %>
<br>

app/views/paragraphs/new.html.erb
<% if @para_last != nil %>
<div class = "cont">Last published paragraph:<br>
  <div class="newpara"> 
    <p class="author">written by <br> <%= @para_last.author %> 
      <% if current_user.try(:id) ==  @para_last.user_id %>
        <br>(you)</p>
      <% else %>
        </p>
      <% end %>  
    <p class="text"> <%= @para_last.parag %></p>
  </div>
</div>
<% end %>

<div class= "instructions">
  <p class = "h_field">Submit your paragraph proposition</p>
<br>

<%= render 'form' %>
</div>

app/views/shared/_footer.html.erb
<div class ="footer">
  Written By Mateusz Wąsowski 2015
  
  <a href ="https://github.com/mateuszwasowski/Written-By-The-Internet"> | GitHub</a>
</div>

app/views/shared/_header.html.erb
<div id = "h_background">
  
<header class="header">
  
  <li><%= link_to "WrittenByTheInternet", root_path %></li>
  
  <% if user_signed_in? %>
    <li><%= "#{current_user.first_name} #{current_user.last_name}" %> | <%= link_to "Sign Out", destroy_user_session_path, :method =>     :delete %> </li>  
  <% else %>
    <li><%= link_to "Log In", new_user_session_path %> | <%= link_to "Sign Up", new_user_registration_path %></li>
  <% end %>
  
</header>
</div>

app/views/shared/_nav.html.erb
<div class= "nav">
  
<% if current_page?(root_path) %>
  <li id = "current_page"><%= link_to "Read", root_path  %></li> 
<% else %>
  <li  ><%= link_to "Read", root_path  %></li> 
<% end %>
  
<% if current_page?(write_path) %>
  <li  id = "current_page"><%= link_to "Write", write_path %></li>
<% else %>
  <li ><%= link_to "Write", write_path %></li>
<% end %>
  
  <% if current_page?(vote_path) || current_page?(paragraphs_path) %>
  <li id = "current_page"><%= link_to "Vote", vote_path %></li>
<% else %>
  <li><%= link_to "Vote", vote_path %></li>
<% end %>
  
</div>